import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/Footer'
import { ProgressBarProvider } from '@/components/ProgressBarProvider'

export const metadata: Metadata = {
  title: 'Flexible',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>
        <ProgressBarProvider>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
        </ProgressBarProvider>
      </body>
    </html>
  )
}
